### ISSUE TITLE
Setup computers

### ISSUE THREAD

**Issue by dmil** [code4policy/2022#1]
- [x] Make sure [Windows and Mac Setup](https://github.com/code4policy/modules/tree/master/setup) are still up-to-date, make any changes needed
- [x] Make sure WSL setup instructions are correct as that may have evolved since last year.
- [x] Make sure M1 Macs are supported properly (both in the setup steps and the various packages we ask students to install in modules). I recall Soma told me that he had to roll back to Python 3.9 for pip installing certain packages on M1 macs, do we need to do anything like that?

**Comment by dmil** [comment]
@traghuram in charge of WSL and M1 Mac, @pcsong33 in charge of intel mac

**Comment by pcsong33** [comment]
Installation instructions for intel mac were good on my end, except for one step in [shell.md](https://github.com/code4policy/modules/blob/master/setup/shell.md). 
For me, running the command 
`sudo subl /etc/shells` 
resulted in the error: 
`Timeout waiting for detached instance to start: No such file or directory`
I troubleshooted the error a little bit (found some stackoverflow posts [here](https://stackoverflow.com/questions/49048720/unable-to-modify-etc-shells-on-macos-to-include-brew-installed-version-of-bash/49049781) and [here](https://unix.stackexchange.com/questions/454604/why-i-cant-add-fish-to-etc-shells) on the issue), and found that running the command
`echo /usr/local/bin/bash | sudo tee -a /etc/shells`
solved the issue. Would be good to confirm with you @traghuram to see if you run into the same issue.

**Comment by traghuram** [comment]
WSL instructions seemed to work - the Windows docs have changed a bit though, so the hard part was figuring out what was relevant. I can make a PR with updated instructions if helpful. But no one should run into serious issues. Working on M1 now

**Comment by traghuram** [comment]
> Would be good to confirm with you @traghuram to see if you run into the same issue.![image](https://user-images.githubusercontent.com/29411525/147777370-e3b604e3-e938-4e55-af4e-5549ece503bd.png)
Yes I did, and your fix seemed to work for me, but I also ran into an additional error:

`login: /usr/local/bin/bash: No such file or directory
`
I solved it by changing my login shell, as detailed on StackOverflow [here](https://stackoverflow.com/questions/55562522/when-i-start-my-terminal-i-get-login-usr-local-bin-bash-no-such-file-or-dire)

I was also asked to add Homebrew to PATH on my machine, as detailed below (I think this is a Mac Mini thing only). Not sure if I was supposed to, but Homebrew strongly recommended it:

![image](https://user-images.githubusercontent.com/29411525/147777370-e3b604e3-e938-4e55-af4e-5549ece503bd.png)

**Comment by dmil** [comment]
Glad WSL instructions are working-ish. Please do make any updates necessary to the instructions in a PR, thanks!

A few questions/thoughts @traghuram:

-  Do you know if WSL2 is default now or did you end up installing the older WSL? Last year WSL2 was out, but it was annoying to install so we stuck to the older version. 
- W/r/t the default shell, is it `zsh`? Mac defaults to `zsh` now, so if WSL is also defaulting to `zsh` we should just change all the course materials to use that instead of trying to force everyone to switch to `bash` I think...
- Ah, interesting w/r/t homebrew. I'm wondering if the install script automatically puts that in zprofile? I don't remember putting it in mine, but when I ran `cat ~/.zprofile` I found that line in there, which makes me think the homebrew installer just did it for me. Can you cat the zprofile and see if it is in there twice now or just once?

**Comment by traghuram** [comment]
Re: WSL instructions - will do. 

On your questions:

- WSL2 is the default if you install it using `wsl --install`. I did this and reverted the version to WSL1 in a single step: `wsl --set-default-version 1`. The catch is that only works if you have Windows 10 updated past a certain version (1903). If you have an older version, there's a manual way to install WSL1. So I would recommend sticking with WSL1 unless we think most people will have updated Windows computers.
- I *think* bash is default for WSL and that I would have to sudo install zsh on Ubuntu. zsh is default for the M1 Macs too, and that was actually quite annoying to troubleshoot. If we stick with zsh, I think it wouldn't be too bad for [Windows folks](https://www.howtogeek.com/258518/how-to-use-zsh-or-another-shell-in-windows-10/) to update
- Re homebrew, I only see that line once when I cat zprofile, and I think it's because I ran those two lines after I installed it. I think brew asked me to add the line to zprofile manually, because the it's located in a different place on M1 macs. 

Lastly, I had to make one other modification to the setup for everything to work on M1 macs. I added the PATH line that was in zprofile to the top of bash_profile, since we switched from zsh to bash. Doing that seems to make everything work, but I made that step up, so it's not sanctioned by StackOverFlow or anyone online - everyone I can find seems to be sticking with zsh. So we may run into problems later, but so far so good!
