### ISSUE TITLE
GitHub Classroom

### ISSUE THREAD

**Issue by dmil** [code4policy/2022#7]
Make sure the GitHub Classroom assignments still work. Maybe purge the code4policy org of repos from previous students. Is there a way to do that without students losing those repos?

**Comment by dmil** [comment]
- [ ] make 2022 github classroom
- [ ] see if there is a way to purge old repos without students losing their work

**Comment by traghuram** [comment]
Re: removing repos from the org without deleting them - one idea I had was to remove people from the organization, since it seems like [they retain any local clones](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/removing-a-collaborator-from-a-personal-repository) of those repos. To test this, I can clone one of the assignments on my account, then you can remove me from the org and we can see if I still retain my local clone.

If not, then @dmil do you remember how you purged people from 2020? I can't seem to find any of their repos in the org, so did you just delete them?

Also, cowsay and simple-website are still throwing server errors - should I investigate further, or do you have an idea of what's going on?

**Comment by traghuram** [comment]
Ready to be closed - we will remove all of last year's students but keep their repos in the org.

**Comment by dmil** [comment]
Thanks, yeah we didn't use github classroom in 2020 so they were just forking the repo into their own accounts.

**Comment by dmil** [comment]
will wait for us to chat before closing
